[project]
name = "gru-nicegui"
version = "0.3.1"
authors = [{name="Cimbali", email="me@cimba.li" }]
description = "NiceGUI GUI for Gru, the ESO addon manager."
license = "EUPL-1.2"
requires-python = ">=3.9"
dependencies = [
    "gru-eso",
    "nicegui",
    "requests",
    "pywebview",
]

[project.optional-dependencies]
build = ["pyinstaller"]

[project.scripts]
gru-app = "main:run"

[tool.setuptools]
py-modules = ["main"]
packages = ["gru_ui", "pages"]

[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"
